apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    {{- include "muffin-currency.labels" . | nindent 4 }}
    app: {{ include "muffin-currency.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "muffin-currency.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
