apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-env
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
data:
{{- $cfg := .Values.config | default dict -}}
{{- $env := $cfg.env | default dict -}}
{{- range $k, $v := $env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
