apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-env
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
data:
  {{- $config := .Values.config | default dict }}
  {{- $env := $config.env | default dict }}
  JDK_JAVA_OPTIONS: {{ $env.JDK_JAVA_OPTIONS | default "" | quote }}