apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-env
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
data:
  JDK_JAVA_OPTIONS: {{ .Values.config.env.JDK_JAVA_OPTIONS | quote }}
