apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.fullname" . }}
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "muffin-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "muffin-wallet.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "muffin-wallet.serviceAccountName" . }}
      volumes:
        - name: application-config-volume
          configMap:
            name: {{ include "muffin-wallet.fullname" . }}
      containers:
        - name: {{ include "muffin-wallet.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: application-config-volume
              mountPath: /app/config
          envFrom:
            - secretRef:
                name: {{ include "muffin-wallet.fullname" . }}
            - configMapRef:
                name: {{ include "muffin-wallet.fullname" . }}-env
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | quote }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}