{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-postgres
  labels:
    app: {{ include "muffin-wallet.name" . }}-postgres
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "muffin-wallet.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "muffin-wallet.name" . }}-postgres
        {{- include "muffin-wallet.labels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: {{ .Values.postgresql.port }}
          envFrom:
            - secretRef:
                name: {{ include "muffin-wallet.fullname" . }}-postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
{{- end }}
